### ISSUE TITLE
Move this repository to mt-mods

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/protector#5]
Disclaimer:
_This is not attempt to throw this away and also not meant to hint that I would not like to keep maintaining this repo. Feedback that includes either is completely invalid._

That said I think that it might be better to maintain this under wider community and a bit more centralized access control.
I could always invite contributors here but I think it is not very good approach.
Or I could handle all pull requests myself but that also is not optimal workflow.

Therefore I propose that this repository will be moved under https://github.com/mt-mods and maintained there.

Added this issue here for feedback / opinions on moving this repo under mt-mods org.

@BuckarooBanzay @SwissalpS @OgelGames opinions on this?

**Comment by S-S-X** [comment]
One thing I can think of that would go against moving this repository into mt-mods would be merging modifications, features and fixes into original upstream repository.

Doing so would make maintaining this separate repository basically useless and would just generate some extra workload.

If upstream will be active enough then correct solution would be merging stuff and leaving this repository behind (remove it, let it be my personal playground, whatever).

**Comment by BuckarooBanzay** [comment]
> That said I think that it might be better to maintain this under wider community and a bit more centralized access control.

Sounds good 👍 that was one of the ideas of the `mt-mods` org..

> One thing I can think of that would go against moving this repository into mt-mods would be merging modifications, features and fixes into original upstream repository.

Judging from Tenplus1's reactions to the PR's i made i don't think there will be much going on on that front 😞 

Can we still see that we can pull the latest changes from the notabug-repo, should be very much doable, even automated (i started something like that here: https://github.com/minetest-mirrors, this is just for mirroring though)

**EDIT**: also: the technic-repo works like this: https://github.com/mt-mods/technic/pull/24

**Comment by S-S-X** [comment]
Repository moved under mt-mods
